### ISSUE TITLE
Running error on VariantQC

### ISSUE THREAD

**Issue by no7ren** [BimberLab/DISCVRSeq#149]
Here is the log of the running. The problem seems to be related to generated json objects. 

14:07:21.241 INFO  ProgressMeter - Traversal complete. Processed 8934114 total variants in 55.9 minutes.
14:07:23.738 INFO  VariantQC - Shutting down engine
[October 7, 2021 2:07:23 PM UTC] com.github.discvrseq.walkers.variantqc.VariantQC done. Elapsed time: 55.98 minutes.
Runtime.totalMemory()=1276641280
***********************************************************************

UNEXPECTED ERROR: Comparison method violates its general contract!

***********************************************************************
Please, search for this error in our issue tracker or post a new one:
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeLo(TimSort.java:777)
        at java.util.TimSort.mergeAt(TimSort.java:514)
        at java.util.TimSort.mergeCollapse(TimSort.java:441)
        at java.util.TimSort.sort(TimSort.java:245)
        at java.util.Arrays.sort(Arrays.java:1512)
        at java.util.ArrayList.sort(ArrayList.java:1464)
        at java.util.Collections.sort(Collections.java:177)
        at com.github.discvrseq.walkers.variantqc.ReportDescriptor.getSortedRows(ReportDescriptor.java:148)
        at com.github.discvrseq.walkers.variantqc.TableReportDescriptor.getReportJson(TableReportDescriptor.java:66)
        at com.github.discvrseq.walkers.variantqc.SectionJsonDescriptor.getConfig(SectionJsonDescriptor.java:44)
        at com.github.discvrseq.walkers.variantqc.HtmlGenerator.generateHtml(HtmlGenerator.java:108)
        at com.github.discvrseq.walkers.variantqc.VariantQC.onTraversalSuccess(VariantQC.java:492)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1067)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at com.github.discvrseq.Main.main(Main.java:50)

**Comment by no7ren** [comment]
Another finding not related to this is the multi-threading is always up to 4 cores no matter how many you setup with threads

**Comment by bbimber** [comment]
The latter might be expected. The multi-threading is now perfect in VariantQC. We still use GATK's engine to iterate one source variant at a time. Internally, VariantQC actually creates many instances of VariantEval (which is what collected the stratified data). We use multiple threads to variants to each of those instances. The number of useful threads depends on how the run is configured. I thought this would generally use more than 4 threads, but it might depend on your input.

Anyway, if you dont mind can we try one last iteration of logging? This should have a broader error catching net, and will log the input list if sorting fails like your stracktrace suggests (in theory). 

https://prime-seq.ohsu.edu/_webdav/Labs/Bimber/Collaborations/Public/%40files/DISCVRSeq-1.3.6-3-g6b685d8-SNAPSHOT.jar

**Comment by bbimber** [comment]
@no7ren OK, this is progress. Would you mind doing one more iteration? I am hopeful this will log enough to see what's happening.

and yes, the version I made last catches the error during sorting and will go ahead with the unsorted input.

https://prime-seq.ohsu.edu/_webdav/Labs/Bimber/Collaborations/Public/%40files/DISCVRSeq-1.3.6-3-g6b685d8-SNAPSHOT.jar

**Comment by no7ren** [comment]
It is true. The new fixed version does not generate any errors. Great, thank you for the help.
