### ISSUE TITLE
Couldn't find state for xxx.scaffold

### ISSUE THREAD

**Issue by Yixiangzhang1996** [BimberLab/DISCVRSeq#52]
Hello Everyone,

I encountered the following error when I ran VariantQC.
Does anyone know how to resolve this issue?

Thanks,

Andrew

java -jar DISCVRSeq-1.07.jar VariantQC \
      -R h.fasta \ 
      -V Siple.vcf.gz  \
      -O output.html
******************************************************************************************************
10:26:38.545 INFO  VariantQC - ------------------------------------------------------------
10:26:38.546 INFO  VariantQC - DISCVR-seq Toolkit v1.07
10:26:38.546 INFO  VariantQC - For support and documentation go to https://software.broadinstitute.org/gatk/
10:26:38.546 INFO  VariantQC - Executing as zyx@node03 on Linux v3.10.0-514.el7.x86_64 amd64
10:26:38.547 INFO  VariantQC - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_152-release-1056-b12
10:26:38.547 INFO  VariantQC - Start Date/Time: October 11, 2019 10:26:38 AM CST
10:26:38.547 INFO  VariantQC - ------------------------------------------------------------
10:26:38.547 INFO  VariantQC - ------------------------------------------------------------
10:26:38.547 INFO  VariantQC - HTSJDK Version: 2.18.0
10:26:38.548 INFO  VariantQC - Picard Version: unknown
10:26:38.548 INFO  VariantQC - HTSJDK Defaults.COMPRESSION_LEVEL : 2
10:26:38.548 INFO  VariantQC - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
10:26:38.548 INFO  VariantQC - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
10:26:38.548 INFO  VariantQC - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
10:26:38.548 INFO  VariantQC - Deflater: IntelDeflater
10:26:38.548 INFO  VariantQC - Inflater: IntelInflater
10:26:38.548 INFO  VariantQC - GCS max retries/reopens: 20
10:26:38.548 INFO  VariantQC - Requester pays: disabled
10:26:38.548 INFO  VariantQC - Initializing engine
10:26:40.168 INFO  FeatureManager - Using codec VCFCodec to read file file:///home1/zyx/projects/aphid_evolution/data/3.result/MERGE.VCF/VariantQC/32samples.vcf
10:26:41.008 INFO  VariantQC - Done initializing engine
10:26:41.108 INFO  VariantQC - Reference has too many contigs, subsetting to the first 40
log4j:WARN No appenders could be found for logger (org.reflections.Reflections).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
10:26:42.945 INFO  VariantEvalChild - Creating 3 combinatorial stratification states
10:26:43.385 INFO  VariantQC - Reference has too many contigs, subsetting to the first 40
10:26:43.403 INFO  VariantEvalChild - Creating 123 combinatorial stratification states
10:26:43.891 INFO  VariantEvalChild - Creating 99 combinatorial stratification states
10:26:44.417 INFO  VariantEvalChild - Creating 198 combinatorial stratification states
10:26:44.991 INFO  VariantQC - Reference has too many contigs, subsetting to the first 40
10:26:44.997 INFO  VariantEvalChild - Creating 4059 combinatorial stratification states
10:26:45.302 INFO  VariantQC - Reference has too many contigs, subsetting to the first 40
10:26:45.305 INFO  VariantEvalChild - Creating 246 combinatorial stratification states
10:26:45.645 INFO  VariantEvalChild - Creating 6 combinatorial stratification states
10:26:46.035 INFO  VariantEvalChild - Creating 6 combinatorial stratification states
10:26:46.036 INFO  ProgressMeter - Starting traversal
10:26:46.036 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
10:26:48.338 INFO  VariantQC - Shutting down engine
[October 11, 2019 10:26:48 AM CST] com.github.discvrseq.walkers.variantqc.VariantQC done. Elapsed time: 0.17 minutes.
Runtime.totalMemory()=1346895872
***********************************************************************

UNEXPECTED ERROR: Couldn't find state for scaf_100267 at node org.broadinstitute.hellbender.tools.walkers.varianteval.stratifications.manager.StratNode@3a3e78f

***********************************************************************
Please, search for this error in our issue tracker or post a new one:
org.broadinstitute.hellbender.exceptions.GATKException: Couldn't find state for scaf_100267 at node org.broadinstitute.hellbender.tools.walkers.varianteval.stratifications.manager.StratNode@3a3e78f
	at org.broadinstitute.hellbender.tools.walkers.varianteval.stratifications.manager.StratNode.find(StratNode.java:76)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.stratifications.manager.StratNode.find(StratNode.java:78)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.stratifications.manager.StratificationManager.getKeys(StratificationManager.java:173)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.stratifications.manager.StratificationManager.values(StratificationManager.java:224)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.VariantEval.getEvaluationContexts(VariantEval.java:635)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.VariantEval.processComp(VariantEval.java:566)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.VariantEval.doApply(VariantEval.java:538)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.VariantEval$PositionAggregator.callDoApply(VariantEval.java:473)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.VariantEval$PositionAggregator.addVariant(VariantEval.java:454)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.VariantEval$PositionAggregator.access$100(VariantEval.java:445)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.VariantEval.apply(VariantEval.java:487)
	at com.github.discvrseq.walkers.variantqc.VariantQC.apply(VariantQC.java:370)
	at org.broadinstitute.hellbender.engine.VariantWalker.lambda$traverse$0(VariantWalker.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalker.traverse(VariantWalker.java:104)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at com.github.discvrseq.Main.main(Main.java:50)

**Comment by bbimber** [comment]
Hello,

Can you please check out the --maxContigs argument?  Based on this stack and your error, I'd guess this might be the cause.  I'll grant VariantQC might be able to handle this more gracefully, but can you please set this to the number of contigs in your genome?

Thanks,
Ben
